if(!require(shiny)) install.packages('shiny',repos='http://cran.rstudio.com/')
if(!require(shinythemes)) install.packages('shinythemes', repos='http://cran.rstudio.com/')
if(!require(DT)) install.packages('DT', repos='http://cran.rstudio.com/')
if(!require(dplyr)) install.packages('dplyr', repos='http://cran.rstudio.com/')
if(!require(ggplot2)) install.packages('ggplot2', repos='http://cran.rstudio.com/')
if(!require(gridExtra)) install.packages('gridExtra', repos='http://cran.rstudio.com/')
if(!require(shinydashboard)) install.packages('shinydashboard', repos='http://cran.rstudio.com/')
if(!require(parsedate)) install.packages('parsedate', repos='http://cran.rstudio.com/')
if(!require(devtools)) install.packages('devtools', repos='http://cran.rstudio.com/')
if(!require(AnomalyDetection)) devtools::install_github('twitter/AnomalyDetection')
